Repository nc1z/Asset-Screener-App, pull requests merged in 2022-12, with the labels that each got.

#35 [images] Shifted into public folder and refactor for different browsers
  client/index.html
  client/public/android-chrome-192x192.png
  client/public/android-chrome-256x256.png
  client/public/apple-touch-icon.png
  client/public/browserconfig.xml
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/images/bar-chart-16.png
  client/public/images/bar-chart.png
  client/public/images/undraw-btc.svg
  client/public/images/undraw-crypto.svg
  client/public/images/undraw-profile.svg
  client/public/images/undraw-savings.svg
  client/public/mstile-150x150.png
  client/public/safari-pinned-tab.svg
  client/public/site.webmanifest
  client/src/components/Navbar.jsx
  client/src/components/PortfolioTable.jsx
  client/src/routes/Account.jsx
  client/src/routes/Ticket.jsx
  client/src/routes/Watchlist.jsx
Labels: bug

#37 [Readme] readme updated with app description and image snippets
  README.md
Labels: documentation

#48 update README.md
  README.md
Labels: documentation

#49 [readme] issue #27 - updated with wireframe images
  README.md
Labels: documentation

#50 issue #42 added pagination logic to backend
  server/src/routes/markets.js
Labels: enhancement

#51 refactored pagination logic
  server/src/routes/markets.js
Labels: bug

#52 [Pagination, Home, Dashboard] #issue 42 - Created Pagination Feature
  client/src/components/Dashboard.jsx
  client/src/components/Pagination.jsx
  client/src/components/PaginationButton.jsx
  client/src/routes/Home.jsx
Labels: enhancement
